### ISSUE TITLE
Not working on 1.9.2

### ISSUE THREAD

**Issue by brian-pantano** [sstephenson/ruby-yui-compressor#23]
ruby -v
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]

> > compressor = YUI::JavaScriptCompressor.new(:munge => true)
> > => #<YUI::JavaScriptCompressor:0x0000000530fc78 @options={:charset=>"utf-8", :line_break=>nil, :munge=>true, :optimize=>true, :preserve_semicolons=>false}, @command="java -jar /usr/local/rvm/gems/ruby-1.9.2-p290/gems/yui-compressor-0.9.6/lib/yui/../yuicompressor-2.4.4.jar --type js --charset utf-8">
> > compressor.compress('(function () { var foo = {}; foo["bar"] = "baz"; })()')
> > NoMethodError: undefined method `map' for #<String:0x0000000530ea30>
> >     from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:29:in`command'
> >     from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:68:in `block in compress'
> >     from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:117:in`streamify'
> >     from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:66:in `compress'
> >     from (irb):8
> >     from /usr/local/rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in`<main>'

**Comment by Syr3f** [comment]
Works fine on my 1.9.2-p180

**Comment by stevecrozz** [comment]
I made sure to include this version of ruby in my most recent tests when I added windows compatibility:
https://github.com/sstephenson/ruby-yui-compressor/commit/f21aec7e9a5bc1b2a6b4e5c25e0f7b021d82d14d

It is passing the test suite now, so I think this issue is now moot. Please reopen if you continue having this issue.
